CREATE UNIQUE INDEX "activity_intervals_id_session_unique" ON "activity_intervals" USING btree ("id","session_id");--> statement-breakpoint
CREATE UNIQUE INDEX "raw_session_records_id_session_unique" ON "raw_session_records" USING btree ("id","session_id");--> statement-breakpoint
CREATE UNIQUE INDEX "session_segments_id_raw_record_unique" ON "session_segments" USING btree ("id","raw_session_record_id");--> statement-breakpoint
CREATE UNIQUE INDEX "session_turns_id_session_unique" ON "session_turns" USING btree ("id","session_id");--> statement-breakpoint
ALTER TABLE "raw_session_records" ADD CONSTRAINT "raw_session_records_activity_interval_session_fk" FOREIGN KEY ("activity_interval_id","session_id") REFERENCES "public"."activity_intervals"("id","session_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_relationships" ADD CONSTRAINT "session_relationships_source_turn_session_fk" FOREIGN KEY ("source_turn_id","source_session_id") REFERENCES "public"."session_turns"("id","session_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_segment_embeddings" ADD CONSTRAINT "session_segment_embeddings_segment_raw_record_fk" FOREIGN KEY ("segment_id","raw_session_record_id") REFERENCES "public"."session_segments"("id","raw_session_record_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_segments" ADD CONSTRAINT "session_segments_activity_interval_session_fk" FOREIGN KEY ("activity_interval_id","session_id") REFERENCES "public"."activity_intervals"("id","session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_segments" ADD CONSTRAINT "session_segments_turn_session_fk" FOREIGN KEY ("turn_id","session_id") REFERENCES "public"."session_turns"("id","session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_segments" ADD CONSTRAINT "session_segments_raw_record_session_fk" FOREIGN KEY ("raw_session_record_id","session_id") REFERENCES "public"."raw_session_records"("id","session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_turns" ADD CONSTRAINT "session_turns_activity_interval_session_fk" FOREIGN KEY ("activity_interval_id","session_id") REFERENCES "public"."activity_intervals"("id","session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_turns" ADD CONSTRAINT "session_turns_raw_record_session_fk" FOREIGN KEY ("raw_session_record_id","session_id") REFERENCES "public"."raw_session_records"("id","session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_turns" ADD CONSTRAINT "session_turns_parent_session_fk" FOREIGN KEY ("parent_turn_id","session_id") REFERENCES "public"."session_turns"("id","session_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_intervals" ADD CONSTRAINT "activity_intervals_ordinal_check" CHECK ("activity_intervals"."ordinal" >= 0);--> statement-breakpoint
ALTER TABLE "activity_intervals" ADD CONSTRAINT "activity_intervals_settled_coherence_check" CHECK (("activity_intervals"."status" = 'active' and "activity_intervals"."settled_at" is null) or ("activity_intervals"."status" = 'settled' and "activity_intervals"."settled_at" is not null));--> statement-breakpoint
ALTER TABLE "raw_session_records" ADD CONSTRAINT "raw_session_records_snapshot_ordinal_check" CHECK ("raw_session_records"."snapshot_ordinal" >= 0);--> statement-breakpoint
ALTER TABLE "session_relationships" ADD CONSTRAINT "session_relationships_no_self_reference_check" CHECK ("session_relationships"."source_session_id" <> "session_relationships"."target_session_id");--> statement-breakpoint
ALTER TABLE "session_segments" ADD CONSTRAINT "session_segments_ordinal_check" CHECK ("session_segments"."ordinal" >= 0);--> statement-breakpoint
ALTER TABLE "session_turns" ADD CONSTRAINT "session_turns_ordinal_check" CHECK ("session_turns"."ordinal" >= 0);--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_status_check" CHECK ("sessions"."status" in ('active', 'completed'));
