#!/usr/bin/env bash
# SGA-221 spike: build the bun-compiled single-binary saga.
#
# Two steps:
#   1. Regenerate packages/db/src/embedded-migrations.ts — the drizzle migrations
#      inlined as plain TS string literals (dual-runtime-safe static bundle). A
#      compiled binary has no repo tree, so DEFAULT_MIGRATIONS_FOLDER cannot read
#      packages/db/drizzle/*.sql; database.ts materializes these literals to a temp
#      dir instead. Regenerate whenever a migration is added.
#   2. bun build --compile the CLI entry (apps/cli/src/main.ts) into ./saga.
#
# Requires bun on PATH (mise: `mise install bun` pins 1.3.14 for this repo family).
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
command -v bun >/dev/null || { echo "bun not on PATH (try: mise install bun)"; exit 1; }

echo "[1/2] regenerate packages/db/src/embedded-migrations.ts"
GEN="$(mktemp -t gen-embedded-XXXX).ts"
cat > "$GEN" <<'TS'
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL(process.argv[2], import.meta.url));
const drizzleDir = join(root, 'packages/db/drizzle');
const journal = readFileSync(join(drizzleDir, 'meta/_journal.json'), 'utf8').trim();
const sqlFiles = readdirSync(drizzleDir).filter((f) => f.endsWith('.sql')).toSorted();
const l = [
  '// GENERATED by spike/sga-221/build.sh — do not edit by hand.',
  '// Drizzle migrations inlined as literals so a compiled single-binary (no repo',
  '// tree) can still read them. Regenerate after adding a migration.',
  '',
  `export const embeddedJournal = ${journal};`,
  '',
  'export const embeddedSql: Record<string, string> = {',
];
for (const f of sqlFiles) {
  const tag = f.replace(/\.sql$/, '');
  l.push(`  ${JSON.stringify(tag)}: ${JSON.stringify(readFileSync(join(drizzleDir, f), 'utf8'))},`);
}
l.push('};');
writeFileSync(join(root, 'packages/db/src/embedded-migrations.ts'), `${l.join('\n')}\n`);
process.stdout.write(`  wrote embedded-migrations.ts (${sqlFiles.length} migrations)\n`);
TS
# process.argv[2] is resolved relative to the temp file's URL; pass a path back to REPO.
( cd "$REPO" && bun run "$GEN" "file://$REPO/" )
rm -f "$GEN"
( cd "$REPO" && pnpm run format >/dev/null 2>&1 || true )

echo "[2/2] bun build --compile"
( cd "$REPO" && bun build --compile apps/cli/src/main.ts --outfile "$HERE/saga" )
ls -lh "$HERE/saga" | awk '{print "  binary:", $5, $NF}'
